nginx:
  image: "nginx:1.9"
  container_name: nginx
  ports:
    - 443:443
    - 80:80
  links:
    - registry:registry
  volumes:
    - ./nginx/:/etc/nginx/conf.d/
registry:
  image: registry:latest
  container_name: registry
  ports:
    - "5000:5000"
  environment:
    - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/data
    - REGISTRY_STORAGE_DELETE_ENABLED=true
  volumes:
    - ./data:/data    
  restart: unless-stopped

